const mongoose = require('mongoose');

const devoteeSchema = new mongoose.Schema({
    groupId: { type: mongoose.Schema.Types.ObjectId, ref: "Group" },
    mobileNo: { type: String, required: true, unique: true },
    name: { type: String, required: true },
    motherName: { type: String },
    fatherName: { type: String },
    dateOfBirth: { type: Date, required: true },
    gender: { type: String, enum: ['Male', 'Female', 'Other'], required: true },
    email: { type: String },
    city: { type: String },
    state: { type: String },
    country: { type: String },
    address: { type: String },
    isMarried: { type: Boolean, default: false },
    dateOfMarriage: { type: Date, default: null },
    education: { type: String },
    occupation: { type: String },
    companyName: { type: String },
    associationYear: { type: Number, default: 0 },
    associatedBy: { type: String },
    firstIskconCenter: { type: String },
    isInitiated: { type: Boolean, default: false },
    initiationName: { type: String },
    initiationTitle: { type: String },
    initiationPlace: { type: String },
    initiationDate: { type: Date },
    spiritualGuru: { type: String },
    initiationPlace2: { type: String },
    initiationDate2: { type: Date },
    spiritualGuru2: { type: String },
    devotionalCourses: [{ type: String }],
    profilePicture: { type: String },
    chantingRounds: { type: Number, default: 0 },
    isAdmin: { type: Boolean, default: false },
    isCounsellor: { type: Boolean, default: false },
    postInTemple: { type: String },
    userType: { type: String, enum: ['Well Wisher', 'Devotee', 'Donor'], default: 'Devotee' },
    counsellorName: { type: String },
    //proper reference link to counsellor (who is also a Devotee)
    counsellorId: { type: mongoose.Schema.Types.ObjectId, ref: 'Devotee' },
    otherCounsellorDetails: {
        name: { type: String },
        mobileNo: { type: String }
    },
    spouseDetails: {
        name: { type: String },
        mobileNo: { type: String },
        dateOfBirth: { type: Date },
        chantingRounds: { type: Number },
        isInitiated: { type: Boolean, default: false },
        initiationName: { type: String },
        initiationTitle: { type: String },
        initiationPlace: { type: String },
        initiationDate: { type: Date },
        spiritualGuru: { type: String },
        initiationPlace2: { type: String },
        initiationDate2: { type: Date },
        spiritualGuru2: { type: String },
        profilePicture: { type: String },
    },
    childrenDetails: [{
        name: { type: String },
        mobileNo: { type: String },
        dateOfBirth: { type: Date },
        chantingRounds: { type: Number },
        isInitiated: { type: Boolean, default: false },
        initiationName: { type: String },
        initiationTitle: { type: String },
        initiationPlace: { type: String },
        initiationDate: { type: Date },
        profilePicture: { type: String }
    }]
}, { timestamps: true });

module.exports = mongoose.model('Devotee', devoteeSchema);